
wandb:
  enabled: false
  project: "barlow-twins-graph"
  run_name: "gps"

meta:
  test: true
  seed: 2136
  num_workers: 4
  save_model_freq: 100 # 0 means no saving
  save_model_path: "models/bt_gps"
  cache_path: null

train:
  epochs: 200
  lr: 1e-3
  lr_scheduler: true
  batch_size: 16
  lambd: 0.0051
  weight_decay: 1e-6
  lars: false
  
encoder:
  emb_dim: 512
  pe_dim: 32
  num_layers: 4
  dropout: 0.5
  norm: "batch" # []"batch", "layer", "graph", null]
  attn_type: "multihead" # "multihead", "performer"

