wandb:
  run_name: "pretrain_linear_1024_freeze"
  enabled: true
  project: "gin-mdd"

meta:
  test: true
  seed: 2133

train:
  epochs: 150
  lr: 1e-3
  lr_scheduler: true
  batch_size: 256

classifier:
  linear: true

encoder:
  emb_dim: 1024
  hidden_channels: 2048
  num_layers: 2
  dropout: 0.5
  emb_style: "concat" # []"none", "replace", "concat"]
  norm: "batch" # []"batch", "layer", "graph", null]
  checkpoint_path: "models/barlow_twins_graph/fmri_enc_ep8.pt" # Can be null
  # checkpoint_path: null
  freeze: true