wandb:
  run_name: "gps"
  enabled: true
  project: "bsnip"

meta:
  test: true
  seed: 2198
  num_workers: 1

train:
  epochs: 150
  lr: 1e-3
  lr_scheduler: true # Best with set to true
  batch_size: 256
  lars: false
  weight_decay: 1e-6

classifier:
  linear: false

encoder:
  emb_dim: 512
  pe_dim: 32
  num_layers: 4
  dropout: 0.5
  norm: "batch" # []"batch", "layer", "graph", null]
  attn_type: "multihead" # "multihead", "performer"
  # checkpoint_path: "models/hfmca_gps_rest+abide/fmri_enc_ep300.pt"
  # checkpoint_path: "models/simclr_gps_rest+abide/fmri_enc_ep25.pt"
  # checkpoint_path: "models/bt_gps_rest+abide/fmri_enc_ep25.pt"
  checkpoint_path: null
  freeze: false
