wandb:
  run_name: "gps_hfmca_ep100_freeze_linear_rest+abide"
  # run_name: "btwins15_512_freeze_kfold"
  # run_name: "hfmca_512_nonemb_rest+abide+bsnip"
  enabled: true
  project: "sex-rest"

meta:
  test: true
  seed: 2198
  num_workers: 1

train:
  epochs: 150
  lr: 1e-3
  lr_scheduler: false # Best with set to true
  batch_size: 256
  lars: false
  # weight_decay: 0 
  weight_decay: 1e-6

classifier:
  linear: true

encoder:
  emb_dim: 512
  pe_dim: 32
  num_layers: 4
  dropout: 0.5
  norm: "batch" # []"batch", "layer", "graph", null]
  attn_type: "multihead" # "multihead", "performer"
  # checkpoint_path: "models/hfmca_nonemb_rest+abide+bsnip/fmri_enc_ep200.pt" # Can be null
  # checkpoint_path: "models/hfmca_gps_rest+abide_newaug/fmri_enc_ep200.pt"
  # checkpoint_path: "models/bt_gps_rest+abide+bsnip+hcp/fmri_enc_ep25.pt"
  checkpoint_path: "models/hfmca_gps_rest+abide/fmri_enc_ep100.pt"
  # checkpoint_path: null
  freeze: true
