wandb:
  enabled: true
  project: "hfmca"
  run_name: "gps_hfmca"

meta:
  test: true
  seed: 2136
  num_workers: 1
  save_model_freq: 50 # 0 means no saving
  save_model_path: "models/gps_hfmca_512"
  cache_path: null

train:
  epochs: 200
  lr: 1e-3
  lr_scheduler: true
  batch_size: 256
  lambd: 0.0051
  weight_decay: 1e-6
  lars: false
  num_views: 9
  
encoder:
  emb_dim: 512
  pe_dim: 32
  num_layers: 4
  dropout: 0.5
  norm: "batch" # "batch", "sigmoid"
  attn_type: "multihead" # "multihead", "performer"
