# defaults:
#   - override hydra/sweeper: optuna
#   - override hydra/sweeper/sampler: tpe

# hydra:
#   sweeper:
#     sampler:
#       seed: 2137
#       consider_magic_clip: true
#     direction: maximize
#     study_name: minigrid
#     storage: null
#     n_trials: 100
#     n_jobs: 1
#     max_failure_rate: 0.0
#     params:
#       lr: range(1e-4, 1e-3, 1e-4)

# dataset: "yelp"

wandb:
  run_name: "sfcn_random_256"
  enabled: true
  project: "sfcn-mdd"

meta:
  test: false
  seed: 2137
  num_workers: 2

train:
  epochs: 100
  lr: 1e-3
  lr_scheduler: True
  batch_size: 8

classifier:
  hidden_dim: 1024

encoder:
  channel_number: [28, 58, 128, 256, 512]
  emb_dim: 256
  checkpoint_path: null # Can be null
  norm_out: 'sigmoid' # ['none', 'sigmoid', 'batch_norm']